AllCops:
  TargetRubyVersion: 2.7
  EnabledByDefault: true

Bundler/GemComment:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Max: 120

Layout/MultilineAssignmentLayout:
  Exclude:
    - 'mb-color.gemspec'

Layout/SpaceAroundOperators:
  EnforcedStyleForExponentOperator: space

Lint/ConstantResolution:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 150
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 500

Metrics/ModuleLength:
  Max: 2000

Metrics/PerceivedComplexity:
  Max: 15

Naming/FileName:
  Exclude:
    - 'lib/mb-color.rb'

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - z
    - r
    - g
    - b
    - a
    - l
    - c
    - h
    - s
    - v

Style/ArrayFirstLast:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Exclude:
    - 'mb-color.gemspec'
    - 'spec/**/*_spec.rb'

# This whole channel is about math.  We can read < and >.
Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/YodaExpression:
  Enabled: false
