AllCops:
  TargetRubyVersion: 2.7
  EnabledByDefault: true

Bundler/GemComment:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/ConstantResolution:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 150
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 500

Metrics/ModuleLength:
  Max: 2000

Metrics/PerceivedComplexity:
  Max: 15

Naming/FileName:
  Exclude:
    - 'lib/mb-color.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
