AllCops:
  TargetRubyVersion: 2.7
  EnabledByDefault: true

Bundler/GemComment:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/ConstantResolution:
  Enabled: false

Metrics/BlockLength:
  Max: 150
  Exclude:
    - 'spec/**/*_spec.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
